### ISSUE TITLE
The job hangs when sql query output more than 60K

### ISSUE THREAD

**Issue by gitckluser** [jenkinsci/sqlplus-script-runner-plugin#15]
We can run the sql query successfully in SQLPLUS.  However, when we run the same sql query via the plugin, the process hangs.  We found that if query output is more than 60KB (no matter standard output / spool the output to file), the process will hang.

Could you please help to check?  Thanks.

sqlplus script runner plugin  1.0.9
jenkins 2.57

**Comment by boaglio** [comment]
Please follow the rules and provide:

-     Jenkins server Operation System;
-     Jenkins version ;
-     Where SQLPlus Script Runner is running (local machine or slave machine);
-     Slave machine Operation System (if applicable);
-     Oracle Database version;
-     Oracle SQL*Plus version;
-     Build log with debug info enabled.

Otherwise is hard to help you.

**Comment by gitckluser** [comment]
Dear Boaglio

Jenkins server Operation System	: CentOS Linux release 7.3.1611 (Core) 
Jenkins version: 2.57
Where SQLPlus Script Runner is running: local
Oracle Database version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
Oracle SQL*Plus version: Release 12.1.0.2.0 Production

When the Jenkins job hangs, we abort the job.  Here is the console output of the build.
[build_log.txt](https://github.com/jenkinsci/sqlplus-script-runner-plugin/files/1516864/build_log.txt)

**Comment by WesleyWeber** [comment]
What happens when you manually run the job through direct command line, batch or bash script? Is it just one of your many SQL files? What exactly is it doing? If it works directly but not through this plugin, that would be interesting. 

Also are you saying 60KB in file size or 60,0000 rows of data?

**Comment by boaglio** [comment]
fixed, please use new version 1.0.11
